# Домашнее задание «Библиотека numpy. Вычислительные задачи»


### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [6]:
import numpy as np

In [15]:
def create_array(n):
    return np.arange(0, 10)[::-1]

In [16]:
create_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
def create_diag_matrix(n):
    return np.diag(np.arange(n, -1,-1), k=0)

In [33]:
create_diag_matrix(3)

array([[3, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [38]:
def sum_diagonal(n):
    matrix = create_diag_matrix(n)
    len_ = len(matrix)
    sum_ = sum(matrix[i][i] for i in range(len_))
    return sum_

In [39]:
sum_diagonal(3)

6

### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3


In [49]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [50]:
b = np.array( [4, 12, -3] )

In [51]:
from numpy import linalg

In [52]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [54]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [61]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)
    
    return np.dot( a, b ) / ( aLength * bLength )

In [83]:
dict_ = {}
for i in range(len(users_stats)):
    a = users_stats[i]
    cos = cosine(a,next_user_stats)
    dict_[i+1]=cos
print(dict_)

{1: 0.19999999999999996, 2: 0.8451542547285165, 3: 0.3999999999999999, 4: 0.7905694150420948, 5: 0.3999999999999999, 6: 0.0, 7: 0.0, 8: 0.9486832980505138, 9: 0.0, 10: 0.0}


In [84]:
similarity = sorted(dict_.items(), key=lambda x: (x[1],x[0]), reverse=True)[0]

In [85]:
print(f'Самый похожий пользователь user_id = {similarity[0]}, косинусное растояние = {similarity[1]}.')

Самый похожий пользователь user_id = 8, косинусное растояние = 0.9486832980505138.
